[package]
name = "tic-tac-toe"
version = "0.1.0"
authors = ["KaleBBuR <45644414+KaleBBuR@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]